#This file is part of azulejo
#
# Author: Pedro
#
#This code takes care of setting up or loading configurations.
#Do not edit this file directly. This is only used for bootstrap, once executed,
#this script will write configurations to ~/.azulejorc.js. If you want to
#personalize shortcuts and geometries, edit that file instead.
#

import json
import os.path

def get_initial_config_content():
    """Returns the initial config values as string."""
    this_dir = os.path.dirname(os.path.abspath(__file__))
    initial_config_path = os.path.join(this_dir, 'initial_config.json')

    config_file = open(initial_config_path, 'r')
    content = config_file.read()
    config_file.close()
    return content

def create_inicial_config_file(conf_filename):
    fw = open(conf_filename, 'w')
    raw_json = get_initial_config_content()
    fw.write(raw_json)
    fw.close()

conf_filename = os.path.expanduser('~/.azulejorc.js')

if not os.path.isfile(conf_filename):
    print "Starting azulejo by creating file: '%s'" %(conf_filename)
    create_inicial_config_file(conf_filename)

print "Reading config file: '%s'" %(conf_filename)
fr = open(conf_filename, 'r')
json_string = fr.read()
fr.close()

conf_data = json.loads(json_string)

