language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
sudo: false
# command to install dependencies
install:
  - pip install mock python-coveralls pytest-cov pytest-pep8 nose
# command to run tests
script:  ./run_tests.sh
after_success:
  - coveralls
