language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - pip install mock python-coveralls pytest-cov pytest-pep8
# command to run tests
script:  py.test -v --cov=azulejo --cov-report=term-missing azulejo/
after_success:
  - coveralls
